"""add driver_locations table

Revision ID: a63c9589b78b
Revises: e0f0a83bd309
Create Date: 2026-05-04 18:32:11.440842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63c9589b78b'
down_revision: Union[str, Sequence[str], None] = 'e0f0a83bd309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'driver_locations', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_locations', type_='unique')
    # ### end Alembic commands ###
